#!/usr/bin/perl
# prot_michelle.pl by michelle treiber
use strict;
use warnings;

# translate RNA into protein sequence

die "usage: prot_michelle.pl <input RNA sequence> \n" unless @ARGV == 1;
my ($rna_seq) = @ARGV;
print "Input file: $rna_seq\n";

open (my $fh, '<:encoding(UTF-8)', $rna_seq) or die "Could not open $rna_seq";
my $row = <$fh>;
while (my $row = <$fh>) {
	chomp($rna_seq);
}

my (%gen_code) =(
	'UUU' => 'F',      'CUU' => 'L',      'AUU' => 'I',      'GUU' => 'V',
	'UUC' => 'F',      'CUC' => 'L',      'AUC' => 'I',      'GUC' => 'V',
	'UUA' => 'L',      'CUA' => 'L',      'AUA' => 'I',      'GUA' => 'V',
	'UUG' => 'L',      'CUG' => 'L',      'AUG' => 'M',      'GUG' => 'V',
	'UCU' => 'S',      'CCU' => 'P',      'ACU' => 'T',      'GCU' => 'A',
	'UCC' => 'S',      'CCC' => 'P',      'ACC' => 'T',      'GCC' => 'A',
	'UCA' => 'S',      'CCA' => 'P',      'ACA' => 'T',      'GCA' => 'A',
	'UCG' => 'S',      'CCG' => 'P',      'ACG' => 'T',      'GCG' => 'A',
	'UAU' => 'Y',      'CAU' => 'H',      'AAU' => 'N',      'GAU' => 'D',
	'UAC' => 'Y',      'CAC' => 'H',      'AAC' => 'N',      'GAC' => 'D',
	'UAA' => ' ',      'CAA' => 'Q',      'AAA' => 'K',      'GAA' => 'E',
	'UAG' => ' ',      'CAG' => 'Q',      'AAG' => 'K',      'GAG' => 'E',
	'UGU' => 'C',      'CGU' => 'R',      'AGU' => 'S',      'GGU' => 'G',
	'UGC' => 'C',      'CGC' => 'R',      'AGC' => 'S',      'GGC' => 'G',
	'UGA' => ' ', 	   'CGA' => 'R',      'AGA' => 'R',      'GGA' => 'G',
	'UGG' => 'W',      'CGG' => 'R',      'AGG' => 'R',      'GGG' => 'G', 
	);
}

my ($protein_seq) = "";
for(my $i = 0; $i < length($rna_seq) - 2; $i += 3)
{
  my ($codon) = substr($rna_seq, $i, 3);
  my $protein_seq .= $genetic_code{$codon};
}
print "Translated protein sequence is $protein";

close $rna_seq;
